/**
 * Multiple Choice Questions: "Frankenstein" by Mary Shelley
 * Source: Project Gutenberg (gutenberg.org) - Book #84
 * Generated by Papersaurus AI Educational Tools
 * 
 * Each question has 5 options (A-E) with exactly one correct answer.
 * See answers.js for detailed explanations of all options.
 */

const questions = [
  {
    "id": 1,
    "question": "What is the subtitle of Mary Shelley's 'Frankenstein'?",
    "options": {
      "A": "The Last Man",
      "B": "The Modern Prometheus",
      "C": "The Gothic Dream",
      "D": "The New Prometheus",
      "E": "The Birth of Science"
    },
    "correctAnswer": "B"
  },
  {
    "id": 2,
    "question": "What event in 1816 directly inspired Mary Shelley to begin writing 'Frankenstein'?",
    "options": {
      "A": "A visit to a galvanism demonstration in London",
      "B": "The death of her infant child",
      "C": "A ghost story challenge proposed by Lord Byron",
      "D": "A nightmare she had after reading Paradise Lost",
      "E": "A university lecture on anatomy she attended in Geneva"
    },
    "correctAnswer": "C"
  },
  {
    "id": 3,
    "question": "How old was Mary Shelley when she began writing 'Frankenstein'?",
    "options": {
      "A": "15",
      "B": "16",
      "C": "18",
      "D": "21",
      "E": "24"
    },
    "correctAnswer": "C"
  },
  {
    "id": 4,
    "question": "What narrative structure does Shelley primarily use in 'Frankenstein'?",
    "options": {
      "A": "A straightforward first-person narrative from Victor's perspective",
      "B": "An omniscient third-person narrator",
      "C": "A series of nested narratives told through letters and multiple narrators",
      "D": "A second-person perspective addressing the reader directly",
      "E": "An epistolary novel composed entirely of letters between Victor and Elizabeth"
    },
    "correctAnswer": "C"
  },
  {
    "id": 5,
    "question": "Which major literary and philosophical work does the creature read and deeply connect with during his self-education?",
    "options": {
      "A": "Homer's 'The Odyssey'",
      "B": "Dante's 'Inferno'",
      "C": "Shakespeare's 'Hamlet'",
      "D": "Milton's 'Paradise Lost'",
      "E": "Rousseau's 'The Social Contract'"
    },
    "correctAnswer": "D"
  },
  {
    "id": 6,
    "question": "What is a central theme explored throughout 'Frankenstein'?",
    "options": {
      "A": "The benefits of unchecked scientific progress",
      "B": "The dangers of ambition and the moral responsibilities of a creator",
      "C": "The superiority of rural life over urban civilization",
      "D": "The importance of organized religion in guiding morality",
      "E": "The triumph of humanity over nature"
    },
    "correctAnswer": "B"
  },
  {
    "id": 7,
    "question": "Why was the first edition of 'Frankenstein' (1818) notable in terms of its authorship?",
    "options": {
      "A": "It was published under Percy Shelley's name",
      "B": "It was published anonymously without identifying Mary Shelley",
      "C": "It was published under the pseudonym 'Currer Bell'",
      "D": "It listed Lord Byron as co-author",
      "E": "It was published under the name 'A Lady'"
    },
    "correctAnswer": "B"
  },
  {
    "id": 8,
    "question": "What does the creature initially request from Victor Frankenstein to end his suffering and isolation?",
    "options": {
      "A": "That Victor grant him a painless death",
      "B": "That Victor introduce him to society as his son",
      "C": "That Victor create a female companion for him",
      "D": "That Victor teach him to read and write properly",
      "E": "That Victor give him enough money to travel far away"
    },
    "correctAnswer": "C"
  },
  {
    "id": 9,
    "question": "Which literary genres does 'Frankenstein' most significantly blend together?",
    "options": {
      "A": "Pastoral poetry and social satire",
      "B": "Gothic fiction and Romanticism",
      "C": "Realism and Naturalism",
      "D": "Picaresque adventure and comedy of manners",
      "E": "Magical realism and postmodernism"
    },
    "correctAnswer": "B"
  },
  {
    "id": 10,
    "question": "What common misconception about 'Frankenstein' persists in popular culture to this day?",
    "options": {
      "A": "That the novel was written by Percy Bysshe Shelley",
      "B": "That the creature could speak fluently from the moment of creation",
      "C": "That the name 'Frankenstein' refers to the monster rather than the scientist who created him",
      "D": "That the novel is set in Transylvania",
      "E": "That Victor Frankenstein used electricity from a kite to animate the creature"
    },
    "correctAnswer": "C"
  }
];

module.exports = { questions };
